name: form_warden
description: A very simple package to help you write robust, resusable and extendable validations to go with your Flutter Forms.
version: 1.0.2
homepage: https://github.com/sarkarshuvojit/form_warden

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

publish_to: https://pub.dev